#!/bin/bash
COUNTER=0					
FILE=$1
POINTER=$2
FILESIZE=$(stat -c%s "$FILE");
ENDLOOP=$(( $POINTER + $FILESIZE ))
echo -en "\xFE\xFE\xFE\xFE" > /dev/ttyUSB0	# Синхронизируем поток данных. После исполнения устройство готово принять младший байт адреса
while [ "$POINTER" -lt $ENDLOOP ]
do
    let HR=POINTER/256
    let LR=POINTER%256
    hLR=`printf "%02X" $LR`
    hHR=`printf "%02X" $HR`
    hBT=`dd if=$FILE bs=1 count=1 skip=$COUNTER 2>/dev/null | hexdump -v -e '/1 "%02X"'`
    echo -en "\xFF\x$hLR\x$hHR\xFF\x$hBT" > /dev/ttyUSB0 	# Паттерн чтения/записи байта в адрес $hHR$hLR

    let COUNTER=COUNTER+1
    let POINTER=POINTER+1
done
echo -en "\xFE" > /dev/ttyUSB0			#  Перевести контроллер в состяние запрета записи данных